### ISSUE TITLE
GhostBSD (FreeBSD): OpenSSL problem w/ net8.0 on v13.2 and net6.0 & net8.0 on v14.0 

### ISSUE THREAD

**Issue by sjsepan3** [sec/dotnet-core-freebsd-source-build#27]
## Overview

I have NOT re-tested it with this this week's release _yet_: dotnet-sdk-8.0.105-freebsd-x64.tar.gz
I'm trying to sort out my results (below), but it appears that for the freebsd dotnet ports (net6.0 and net8.0 tested here)...

-GhostBSD 2024.01.1 (FreeBSD 14.0-STABLE) or later, neither .net6.0 or net8.0 work due to a SSL library, and 
-on GhostBSD 2023.10.1 (FreeBSD 13.2-STABLE) net6.0* works but net 8.0 does not due to SSL librrary issue, 
(* -- only when net6.0 is present but net8.0 is not; after net8.0 is added, cannot build net6.0)

I discovered it on a Dell Optiplex 7020, but did all subsequent tests in VirtualBox.

I don't have actual FreeBSD to test; I tried once in VirtualBox but apparently don't know how to do it right, because the installation wouldn't come up.

## Versions

issue is present for both net6.0 and net8.0  on...

ghostbsd-version:
`24.04.1`
freebsd-version:
`14.0-STABLE`

... and also on ...

ghostbsd-version:
`24.01.1`
freebsd-version:
`14.0-STABLE`

...but only for net8.0* on...

ghostbsd-version:
`23.10.1`
freebsd-version:
`13.2-STABLE`

###  `dotnet --info` (GhostBSD 2024.04.1 or 2024.01.1, net6.0 only):

```
.NET SDK (reflecting any global.json):
 Version:   6.0.403
 Commit:    2bc18bf292

Runtime Environment:
 OS Name:     FreeBSD
 OS Version:  14
 OS Platform: FreeBSD
 RID:         freebsd-x64
 Base Path:   /home/sjsepan/.dotnet/sdk/6.0.403/

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  6.0.403 [/home/sjsepan/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/home/sjsepan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

### `dotnet build` (on a simple console app)(GhostBSD 2024.04.1 or 2024.01.1, only .net6.0):

```
No usable version of libssl was found
Abort trap (core dumped)
```

### `dotnet --info` (GhostBSD 2024.04.1 or 2024.01.1, net6.0 and net 8.0):

```
.NET SDK:
 Version:           8.0.104
 Commit:            034f91fcc0
System.TypeInitializationException: The type initializer for 'Crypto' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.OpenSsl' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
Shared object "libcrypto.so.12" not found, required by "libSystem.Security.Cryptography.Native.OpenSsl.so"
Shared object "libSystem.Security.Cryptography.Native.OpenSsl.so" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/liblibSystem.Security.Cryptography.Native.OpenSsl.so"
Shared object "liblibSystem.Security.Cryptography.Native.OpenSsl.so" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/libSystem.Security.Cryptography.Native.OpenSsl"
Shared object "libSystem.Security.Cryptography.Native.OpenSsl" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/liblibSystem.Security.Cryptography.Native.OpenSsl"
Shared object "liblibSystem.Security.Cryptography.Native.OpenSsl" not found, required by "dotnet"

   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.HashAlgorithmToEvp(String hashAlgorithmId)
   at System.Security.Cryptography.SHA256.Implementation..ctor()
   at System.Security.Cryptography.SHA256.Create()
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetWorkloadVersion()
   at Microsoft.DotNet.Cli.WorkloadCommandParser.GetWorkloadsVersion(WorkloadInfoHelper workloadInfoHelper)
   at Microsoft.DotNet.Cli.CommandLineInfo.PrintInfo()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529
  RID:          freebsd-x64

.NET SDKs installed:
  6.0.403 [/usr/home/sjsepan/.dotnet/sdk]
  8.0.104 [/usr/home/sjsepan/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/home/sjsepan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/usr/home/sjsepan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### `dotnet build` (on a simple console app)(GhostBSD 2024.04.1 or 2024.01.1, .net8.0 also installed):

```
System.TypeInitializationException: The type initializer for 'Crypto' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.OpenSsl' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
Shared object "libcrypto.so.12" not found, required by "libSystem.Security.Cryptography.Native.OpenSsl.so"
Shared object "libSystem.Security.Cryptography.Native.OpenSsl.so" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/liblibSystem.Security.Cryptography.Native.OpenSsl.so"
Shared object "liblibSystem.Security.Cryptography.Native.OpenSsl.so" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/libSystem.Security.Cryptography.Native.OpenSsl"
Shared object "libSystem.Security.Cryptography.Native.OpenSsl" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/liblibSystem.Security.Cryptography.Native.OpenSsl"
Shared object "liblibSystem.Security.Cryptography.Native.OpenSsl" not found, required by "dotnet"

   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.HashAlgorithmToEvp(String hashAlgorithmId)
   at System.Security.Cryptography.HashProviderDispenser.OneShotHashProvider.HashData(String hashAlgorithmId, ReadOnlySpan`1 source, Span`1 destination)
   at System.Security.Cryptography.SHA256.TryHashData(ReadOnlySpan`1 source, Span`1 destination, Int32& bytesWritten)
   at System.Security.Cryptography.SHA256.HashData(ReadOnlySpan`1 source, Span`1 destination)
   at System.Security.Cryptography.SHA256.HashData(ReadOnlySpan`1 source)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Microsoft.DotNet.Cli.Utils.Sha256Hasher.Hash(String text)
   at Microsoft.DotNet.Cli.Utils.ApplicationInsightsEntryFormat.<>c__DisplayClass10_0.<WithAppliedToPropertiesValue>b__1(KeyValuePair`2 p)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.DotNet.Cli.Utils.ApplicationInsightsEntryFormat.WithAppliedToPropertiesValue(Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

### `dotnet --info` (GhostBSD 2023.10.1, net6.0 only):

```
.NET SDK (reflecting any global.json):
 Version:   6.0.403
 Commit:    2bc18bf292

Runtime Environment:
 OS Name:     FreeBSD
 OS Version:  13
 OS Platform: FreeBSD
 RID:         freebsd.13-x64
 Base Path:   /usr/home/sjsepan/.dotnet/sdk/6.0.403/

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  6.0.403 [/usr/home/sjsepan/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/home/sjsepan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

### `dotnet build` (GhostBSD 2023.10.1, net6.0 only):

```
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  ConsoleApp1 -> /usr/home/sjsepan/Documents/Projects/DotNetCore/ConsoleApp1/bin/Debug/net6.0/ConsoleApp1.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.94
```

### `dotnet run` (GhostBSD 2023.10.1, net6.0 only):

`Hello World!`

### `dotnet --info`(GhostBSD 2023.10.1, net6.0 and net8.0):

```
.NET SDK:
 Version:           8.0.104
 Commit:            034f91fcc0
System.TypeInitializationException: The type initializer for 'Crypto' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.OpenSsl' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
Shared object "libcrypto.so.12" not found, required by "libSystem.Security.Cryptography.Native.OpenSsl.so"
Shared object "libSystem.Security.Cryptography.Native.OpenSsl.so" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/liblibSystem.Security.Cryptography.Native.OpenSsl.so"
Shared object "liblibSystem.Security.Cryptography.Native.OpenSsl.so" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/libSystem.Security.Cryptography.Native.OpenSsl"
Shared object "libSystem.Security.Cryptography.Native.OpenSsl" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/liblibSystem.Security.Cryptography.Native.OpenSsl"
Shared object "liblibSystem.Security.Cryptography.Native.OpenSsl" not found, required by "dotnet"

   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.HashAlgorithmToEvp(String hashAlgorithmId)
   at System.Security.Cryptography.SHA256.Implementation..ctor()
   at System.Security.Cryptography.SHA256.Create()
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetWorkloadVersion()
   at Microsoft.DotNet.Cli.WorkloadCommandParser.GetWorkloadsVersion(WorkloadInfoHelper workloadInfoHelper)
   at Microsoft.DotNet.Cli.CommandLineInfo.PrintInfo()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529
  RID:          freebsd-x64

.NET SDKs installed:
  6.0.403 [/usr/home/sjsepan/.dotnet/sdk]
  8.0.104 [/usr/home/sjsepan/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/home/sjsepan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/usr/home/sjsepan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### `dotnet build`(GhostBSD 2023.10.1, net6.0 and net8.0):

```
System.TypeInitializationException: The type initializer for 'Crypto' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.OpenSsl' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
Shared object "libcrypto.so.12" not found, required by "libSystem.Security.Cryptography.Native.OpenSsl.so"
Shared object "libSystem.Security.Cryptography.Native.OpenSsl.so" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/liblibSystem.Security.Cryptography.Native.OpenSsl.so"
Shared object "liblibSystem.Security.Cryptography.Native.OpenSsl.so" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/libSystem.Security.Cryptography.Native.OpenSsl"
Shared object "libSystem.Security.Cryptography.Native.OpenSsl" not found, required by "dotnet"
Cannot open "/usr/home/sjsepan/.dotnet/shared/Microsoft.NETCore.App/8.0.4/liblibSystem.Security.Cryptography.Native.OpenSsl"
Shared object "liblibSystem.Security.Cryptography.Native.OpenSsl" not found, required by "dotnet"

   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.HashAlgorithmToEvp(String hashAlgorithmId)
   at System.Security.Cryptography.HashProviderDispenser.OneShotHashProvider.HashData(String hashAlgorithmId, ReadOnlySpan`1 source, Span`1 destination)
   at System.Security.Cryptography.SHA256.TryHashData(ReadOnlySpan`1 source, Span`1 destination, Int32& bytesWritten)
   at System.Security.Cryptography.SHA256.HashData(ReadOnlySpan`1 source, Span`1 destination)
   at System.Security.Cryptography.SHA256.HashData(ReadOnlySpan`1 source)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Microsoft.DotNet.Cli.Utils.Sha256Hasher.Hash(String text)
   at Microsoft.DotNet.Cli.Utils.ApplicationInsightsEntryFormat.<>c__DisplayClass10_0.<WithAppliedToPropertiesValue>b__1(KeyValuePair`2 p)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.DotNet.Cli.Utils.ApplicationInsightsEntryFormat.WithAppliedToPropertiesValue(Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## NOTES

https://forums.freebsd.org/threads/ld-elf-and-libssl-install-bricked-after-upgrade-from-13-1-to-14-0-release.93384/#post-654375
"14.0 has a newer OpenSSL"

**Comment by sjsepan3** [comment]
UPDATE: no difference with dotnet-sdk-8.0.105-freebsd-x64.tar.gz

**Comment by sjsepan3** [comment]
https://stackoverflow.com/questions/73301049/no-usable-version-of-libssl-was-found-after-inserting-pat-in-azure-self-hosted

"The reason could be because of version issues with Open SSL libraries and .Net core"

**Comment by sjsepan3** [comment]
This post talks about similar issues in the past. Perhaps this is a repeat scenario with a still newer version.

https://dev.to/n3wt0n/no-usable-version-of-the-libssl-was-found-solved-2ffa

"OpenSSL is one of the most common cryptographic libraries used on Linux, and it has multiple versions. Version 1.0 is kind of old, but still heavily used, while 1.1 is the newer version that was relatively recently released.
The problem is that versions 1.0 and 1.1 are not compatible. An application that expects 1.0 cannot build against 1.1, nor run against it.
Many Linux distributions are starting to make OpenSSL 1.1 the new default instead of the version 1.0
And here is the problem: .NET Core 2.1, and all earlier versions, only support OpenSSL 1.0."

**Comment by sec** [comment]
Hi.
Did you first try with `pkg install dotnet` to install package from ports? It should install needed deps like `misc/compat13x` for FreeBSD 14.

At the moment, I've stopped doing 6.x builds as it's EOF soon. 8 and 9 should be working fine - you would just need to install `openssl` in correct version for them to work last time I've checked.

I have one `14.0-RELEASE-p3` with `dotnet` from packages installed and working without any issues. Maybe it's GhostBSD that's have something changed, I would need to find some time and setup VM to check it.

**Comment by sjsepan3** [comment]
I suppose it could be a GhostBSD thing: I looked in the Software Station app and the packages there don't list a 'dotnet' package, but 'linux-dotnet-sdk' (2.1.201) and 'linux-dotnet10-sdk' (1.1.9), so later when I ran across your repo, I happily downloaded and installed manually, by copying into ~/.dotnet (the way I do in my Linux Mint) and setting the $PATH. And this worked with net6.0 in the 13.2 based GhostBSD.

I didn't try 'sudo pkg install dotnet' - or I did and don't remember. When I tried just now, I get "No packages available to install matching 'dotnet' have been found in the repositories".

**Comment by sjsepan3** [comment]
Since I didn't manually install openssl in the past, I figured it was already installed but a different version than dotnet expected.
I tried '**sudo pkg install openssl**' just now and the pkg was found and it installed. Trying dotnet build did not spit out the libssl message this time, but this:

`MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
/usr/home/sjsepan/Documents/Projects/DotNetCore/ConsoleApp1/ConsoleApp1.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.freebsd-x64. No packages exist with this id in source(s): nuget.org
  Failed to restore /usr/home/sjsepan/Documents/Projects/DotNetCore/ConsoleApp1/ConsoleApp1.csproj (in 2.58 sec).

Build FAILED.

/usr/home/sjsepan/Documents/Projects/DotNetCore/ConsoleApp1/ConsoleApp1.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.freebsd-x64. No packages exist with this id in source(s): nuget.org
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.37
`

Note, this is with only net8.0 (8.0.105), installed as described in the previous post.
I do see a ~/.dotnet/packs/Microsoft.NETCore.App.Host.freebsd-x64, and `echo $PATH` include "/home/_username_/.dotnet"

Still, this seems better than the previous error; maybe I need to add something else to the PATH.
**UPDATE**: I was using the wrong dotnet version in the csproj file; it now build with net8.0

**Comment by sec** [comment]
I don't know if GhostBSD have it's own package repositories - if that's the case, then it might miss the newest `dotnet` package.

For the missing packages, you can either:
1. use my private feed - https://github.com/sec/dotnet-freebsd-nuget-feed - there's a link inside - you'll need to add this to your `nuget.config` - I assume you know what to do as .NET dev
2. download the nupkg's by hand (either from release or extract private built artifacts from release) and also add them as nuget source

Again - I haven't touched 6.x in long time, so you have to figure it out yourself - but installing openssl should solve the issue you're having.

Also when installing dotnet by hand - follow this https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install - you will need to setup some ENV's to make it "work" without problems.

Please also try to use proper markdown, it will be easier to read, there's a "Preview" tab you can use :)

**Comment by sjsepan3** [comment]
> I don't know if GhostBSD have it's own package repositories - if that's the case, then it might miss the newest `dotnet` package.
> 
> For the missing packages, you can either:
> 
>     1. use my private feed - https://github.com/sec/dotnet-freebsd-nuget-feed - there's a link inside - you'll need to add this to your `nuget.config` - I assume you know what to do as .NET dev
> 
>     2. download the nupkg's by hand (either from release or extract private built artifacts from release) and also add them as nuget source
> 
> 
> Again - I haven't touched 6.x in long time, so you have to figure it out yourself - but installing openssl should solve the issue you're having.

You've given me a few things to try; Thank You!

> 
> Also when installing dotnet by hand - follow this https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install - you will need to setup some ENV's to make it "work" without problems.
> 

Thank You, I'll look that over, but it looks like what I've used in the past for manual installs on Linux. BTW, I have not set the path to $DOTNET_ROOT/tools because I don't see a tools sub-folder in the extracted archive.

> Please also try to use proper markdown, it will be easier to read, there's a "Preview" tab you can use :)

OK; sorry about the format of the initial post -- it was all composed offline in Pluma over a number of days, and then pasted.

**Comment by sjsepan3** [comment]
UPDATE: I had the Console app still set to look for net6.0; when set to net8.0, the build worked and the app runs.
So the solution was to use the net8.0 build as I have, and install a missing openssl package.

The net6.0 build still gets " error NU1101: Unable to find package Microsoft.NETCore.App.Host.freebsd-x64. No packages exist with this id in source(s): nuget.org", but with net8.0 working it is not critical.

UPDATE:It is possible that I also installed openssl back when I originally installed GhostBSD 2023.06.1, and forgot that step.

**Comment by sec** [comment]
No problem. Closing this, if you need more help, feel free to submit new one or start discussion maybe .

**Comment by sjsepan3** [comment]
> No problem. Closing this, if you need more help, feel free to submit new one or start discussion maybe .

Cool, Thanks!
